### ISSUE TITLE
Add allowSyntheticDefaultImports and esModuleInterop

### ISSUE THREAD

**Issue by texastoland** [mightyiam/tsconfigs#34]
...to browser and Node configs respectively. See [this tweet](https://twitter.com/drosenwasser/status/1003097042653073408).I'm researching potential downsides.

**Comment by mightyiam** [comment]
Hey, @texastoland. I apologise for not getting to this. It's been a long while since you've opened this issue. I have recently added "Review the tsconfigs project" to my personal todo list so I should get to this by the end of May. If you feel that these properties should be added, please feel free to reopen this issue.

**Comment by texastoland** [comment]
I've been using a simpler config lately and lost context. You're welcome to reopen. Hope you're well!
