### ISSUE TITLE
"Types" field is preventing all types to be included automatically

### ISSUE THREAD

**Issue by b13nxx** [mightyiam/tsconfigs#400]
Default configuration for `node-executable` prevents proper Jest integration cuz "types" field is declared with only `Node` inside.

```JSON
{
  "extends": "./_private/executable",
  "compilerOptions": {
    "lib": ["ESNext"],
    "module": "CommonJS",
    "types": [
      "node"
    ]
  }
}
```

**Result:**
![image](https://user-images.githubusercontent.com/4191018/168394197-242d92f5-c66c-4747-bf41-418970df926e.png)

---
We cannot override it by simple declaring the field:

![image](https://user-images.githubusercontent.com/4191018/168394387-557745b9-f895-4477-a196-888690e3567e.png)

It doesn't work.

Without the field, all types are automatically included. That's what TypeScript doc is saying. More info here: https://www.typescriptlang.org/tsconfig#types

**Comment by mightyiam** [comment]
Thank you, @b8kkyn, for using this pacakge and communicating this issue.

This is intentional. I feel that the default TypeScript behavior of including all installed `@types/*` packages is undesired.

I prefer to explicitly include the types. I'm not sure what they are in your case, but I'm sure you could find out.
